# Generated by Django 3.0.8 on 2020-07-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postbody',
            field=models.TextField(blank=True),
        ),
    ]
