# Generated by Django 3.0.8 on 2020-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_postbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortdesc',
            field=models.TextField(blank=True),
        ),
    ]
