# Generated by Django 3.0.8 on 2020-08-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_shortdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shortdesc',
        ),
    ]
