# Generated by Django 3.0.8 on 2020-08-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0002_auto_20200815_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmt',
            old_name='user_id',
            new_name='post_id',
        ),
    ]
