# Generated by Django 3.0.8 on 2020-08-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0003_auto_20200815_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmt',
            name='slug',
        ),
    ]
